SELECT CONCEPT_CD, COUNT (*) FROM

(SELECT CONCEPT_CD FROM OBSERVATION_FACT
WHERE (CONCEPT_CD LIKE 'DEM|RACE%' OR CONCEPT_CD LIKE 'DEM|AGE%' OR CONCEPT_CD LIKE 'DEM|RELIGION%' OR CONCEPT_CD LIKE 'DEM|LANGUAGE%' OR CONCEPT_CD LIKE 'DEM|SEX%') AND PATIENT_NUM IN (SELECT DISTINCT(PATIENT_NUM)
    FROM OBSERVATION_FACT
    WHERE CONCEPT_CD LIKE '%LOINC:1920-8%')) A GROUP BY concept_cd ORDER BY 1;

SELECT  ENCOUNTER_NUM, PATIENT_NUM, CONCEPT_CD FROM OBSERVATION_FACT WHERE /*CONCEPT_CD LIKE '%LOINC:1920-8%' AND*/ PATIENT_NUM=1000000016 AND /*ENCOUNTER_NUM=471794 AND*/ (CONCEPT_CD LIKE 'DEM|RACE%' OR CONCEPT_CD LIKE 'DEM|AGE%' OR CONCEPT_CD LIKE 'DEM|RELIGION%' OR CONCEPT_CD LIKE 'DEM|LANGUAGE%' OR CONCEPT_CD LIKE 'DEM|SEX%');


SELECT OB.PATIENT_NUM,
(SELECT OB2.CONCEPT_CD FROM OBSERVATION_FACT 
FROM OBSERVATION_FACT OB WHERE OB.CONCEPT_CD LIKE '%LOINC:1920-8%'


SELECT SUBSTRING(CONCEPT_CD, 9) AS SEX, COUNT(*) FROM OBSERVATION_FACT WHERE CONCEPT_CD LIKE 'DEM|SEX%' AND PATIENT_NUM IN (SELECT DISTINCT(PATIENT_NUM)
    FROM OBSERVATION_FACT
    WHERE CONCEPT_CD LIKE '%LOINC:1920-8%')
GROUP BY CONCEPT_CD;
